In [143]:
pdf_path='07 ViPNet Coordinator HW 5. Перечень совместимых трансиверов.pdf'

In [ ]:
import fitz # (pymupdf, found this is better than pypdf for our use case, note: licence is AGPL-3.0, keep that in mind if you want to use any code commercially)
from tqdm.auto import tqdm # for progress bars, requires !pip install tqdm 

def text_formatter(text: str) -> str:
    """Performs minor formatting on text."""
    cleaned_text = text.replace("\n", " ").strip() # note: this might be different for each doc (best to experiment)

    # Other potential text formatting functions can go here
    return cleaned_text

# Open PDF and get lines/pages
# Note: this only focuses on text, rather than images/figures etc
def open_and_read_pdf(pdf_path: str) -> list[dict]:
    """
    Opens a PDF file, reads its text content page by page, and collects statistics.

    Parameters:
        pdf_path (str): The file path to the PDF document to be opened and read.

    Returns:
        list[dict]: A list of dictionaries, each containing the page number
        (adjusted), character count, word count, sentence count, token count, and the extracted text
        for each page.
    """
    doc = fitz.open(pdf_path)  # open a document
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):  # iterate the document pages
        text = page.get_text()  # get plain text encoded as UTF-8
        text = text_formatter(text)
        pages_and_texts.append({"page_number": page_number,  # adjust page numbers 
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(". ")),
                                "page_token_count": len(text) / 4,  # 1 token = ~4 chars, see: https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
                                "text": text})
    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[:2]

6it [00:00, 275.64it/s]

[{'page_number': 0,
  'page_char_count': 1080,
  'page_word_count': 264,
  'page_sentence_count_raw': 2,
  'page_token_count': 270.0,
  'text': 'Copyright (c) InfoTeCS. All Rights Reserved     Аппаратные платформы HW100 N1, N2, N3  Модель  Тип  Длина волны, нм  Интерфейс  Тип кабеля  Расстояние, км  Avago  AFBR-5710PZ  SFP  850  LC duplex  MM  0,5  Allied Telesis  AT-SPEX  SFP  1310  LC duplex  MM  2  FINISAR  FTLX8574D3BCV  SFP/SFP+  850  LC duplex  MM  0,4  FTLX8519P3BNL  SFP  850  LC duplex  MM  0,3  FTLF1318P3BTL  SFP  1310  LC duplex  SM  10  MlaxLink  ML-P10G-03DFM-85LD  SFP+  850  LC duplex  MM  0,3  ML-SG-01UTP-SGMRJ  SFP  -  RJ-45  UTP  0,1  Smartoptics  SO-SFP-10GE-T  SFP+  -  RJ-45  -  0,03  Аппаратная платформа HW100 Q1, Q2  Модель  Тип  Длина волны, нм  Интерфейс  Тип кабеля  Расстояние, км  Avago  AFBR-5710PZ  SFP  850  LC duplex  MM  0,5  FINISAR  FTLX8574D3BCV  SFP/SFP+  850  LC duplex  MM  0,4  SNR  SNR-SFP-W35-3-LC  SFP  1310  SC simplex  SM  3  Аппаратная платформа HW1000 Q6  Модель  Тип  Длина волны, нм  Интерфейс  Тип кабеля  Расстояние, км  Avago  AFBR-5710PZ  SFP  850  LC duplex  MM  0,5  Allied Telesis  ViPNet Coordinator HW 5  Перечень совместимых трансиверов  Версия продукта 5.3.2'},
 {'page_number': 1,
  'page_char_count': 1140,
  'page_word_count': 309,
  'page_sentence_count_raw': 1,
  'page_token_count': 285.0,
  'text': 'Модель  Тип  Длина волны, нм  Интерфейс  Тип кабеля  Расстояние, км  AT-SPEX  SFP  1310  LC duplex  MM  2  D-Link  DEM-432XT/B1A  SFP+  1310  LC duplex  SM  10  FINISAR  FTLX8574D3BCV  SFP/SFP +  850  LC duplex  MM  0,4  FTLX8519P3BNL  SFP  850  LC duplex  MM  0,3  FTLF1318P3BTL  SFP  1310  LC duplex  SM  10  Аппаратная платформа HW1000 Q9  Модель  Тип  Длина волны, нм  Интерфейс  Тип кабеля  Расстояние, км  Avago  AFBR-5710PZ  SFP  850  LC duplex  MM  0,5  Allied Telesis  AT-SPEX  SFP  1310  LC duplex  MM  2  Fang Hang  FH-S8512CDL05  SFP  850  LC  MM  0,55  FINISAR  FTLX8574D3BCV  SFP/SFP+  850  LC duplex  MM  0,4  FTLX8519P3BNL  SFP  850  LC duplex  MM  0,3  FTLF1318P3BTL  SFP  1310  LC duplex  SM  10  FS.COM  SFP1G-SX-85  SFP  850  LC duplex  MM  0,55  SFP-10GSR-85  SFP+  850  LC duplex  MM  0,3  HIRSCHMANN  M-SFP-LX/LC  SFP  n/a  LC duplex  MM/SM  0,55 / 25  RBT12SLX-IT3  SFP  1310  LC single  MM/SM  0,55 / 25  RBT12SLX-IT5  SFP  1550  LC single  MM/SM  0,55 / 25  MlaxLink  ML-P10G-03DFM-85LD  SFP+  850  LC duplex  MM  0,3  ML-SG-01UTP-SGMRJ  SFP  -  RJ-45  UTP  0,1  Smartoptics  SO-SFP-10GE-T  SFP+  -  RJ-45  -  0,03'}]

In [145]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,0,1080,264,2,270.00,Copyright (c) InfoTeCS. All Rights Reserved ...
1,1,1140,309,1,285.00,"Модель Тип Длина волны, нм Интерфейс Тип к..."
2,2,1055,291,1,263.75,"Аппаратные платформы HW2000 Q4, Q5 Модель Ти..."
3,3,1150,313,1,287.50,Аппаратная платформа HW5000 Q1 Модель Тип Д...
4,4,1059,299,1,264.75,"Модель Тип Длина волны, нм Интерфейс Тип к..."

In [146]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,6.00,6.00,6.00,6.00,6.00
mean,2.50,1004.00,258.00,1.83,251.00
std,1.87,230.87,92.77,1.60,57.72
min,0.00,540.00,72.00,1.00,135.00
25%,1.25,1056.00,270.75,1.00,264.00
50%,2.50,1069.50,295.00,1.00,267.38
75%,3.75,1125.00,306.50,1.75,281.25
max,5.00,1150.00,313.00,5.00,287.50

In [ ]:
from spacy.lang.ru import Russian # see https://spacy.io/usage for install instructions

nlp = Russian()

# Add a sentencizer pipeline, see https://spacy.io/api/sentencizer/ 
nlp.add_pipe("sentencizer")

In [149]:
for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)
    
    # Make sure all sentences are strings
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]
    
    # Count the sentences 
    item["page_sentence_count_spacy"] = len(item["sentences"])

100%|██████████| 6/6 [00:00<00:00, 725.89it/s]

In [150]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,6.00,6.00,6.00,6.00,6.00,6.00
mean,2.50,1004.00,258.00,1.83,251.00,1.50
std,1.87,230.87,92.77,1.60,57.72,0.84
min,0.00,540.00,72.00,1.00,135.00,1.00
25%,1.25,1056.00,270.75,1.00,264.00,1.00
50%,2.50,1069.50,295.00,1.00,267.38,1.00
75%,3.75,1125.00,306.50,1.75,281.25,1.75
max,5.00,1150.00,313.00,5.00,287.50,3.00

In [151]:
# Define split size to turn groups of sentences into chunks
num_sentence_chunk_size = 10 

# Create a function that recursively splits a list into desired sizes
def split_list(input_list: list, 
               slice_size: int) -> list[list[str]]:
    """
    Splits the input_list into sublists of size slice_size (or as close as possible).

    For example, a list of 17 sentences would be split into two lists of [[10], [7]]
    """
    return [input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]

# Loop through pages and texts and split sentences into chunks
for item in tqdm(pages_and_texts):
    item["sentence_chunks"] = split_list(input_list=item["sentences"],
                                         slice_size=num_sentence_chunk_size)
    item["num_chunks"] = len(item["sentence_chunks"])

100%|██████████| 6/6 [00:00<00:00, 83055.52it/s]

In [152]:
# Create a DataFrame to get stats
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy,num_chunks
count,6.00,6.00,6.00,6.00,6.00,6.00,6.0
mean,2.50,1004.00,258.00,1.83,251.00,1.50,1.0
std,1.87,230.87,92.77,1.60,57.72,0.84,0.0
min,0.00,540.00,72.00,1.00,135.00,1.00,1.0
25%,1.25,1056.00,270.75,1.00,264.00,1.00,1.0
50%,2.50,1069.50,295.00,1.00,267.38,1.00,1.0
75%,3.75,1125.00,306.50,1.75,281.25,1.75,1.0
max,5.00,1150.00,313.00,5.00,287.50,3.00,1.0

In [ ]:
import re

pages_and_chunks = []
for item in tqdm(pages_and_texts):
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}
        chunk_dict["page_number"] = item["page_number"]
        
        joined_sentence_chunk = "".join(sentence_chunk).replace("  ", " ").strip()
        joined_sentence_chunk = re.sub(r'\.([A-Z])', r'. \1', joined_sentence_chunk)
        chunk_dict["sentence_chunk"] = joined_sentence_chunk
        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4 # 1 token = ~4 characters
        
        pages_and_chunks.append(chunk_dict)

len(pages_and_chunks)

100%|██████████| 6/6 [00:00<00:00, 29026.33it/s]

6

In [154]:
# Get stats about our chunks
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count         6.00              6.00              6.00               6.00
mean          2.50            895.00            149.00             223.75
std           1.87            181.41             41.80              45.35
min           0.00            533.00             65.00             133.25
25%           1.25            923.25            157.75             230.81
50%           2.50            948.50            161.50             237.12
75%           3.75            997.00            171.25             249.25
max           5.00           1012.00            175.00             253.00

In [106]:
df = df[df['page_number'] > 0]

In [155]:
# Get stats about our chunks
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count         6.00              6.00              6.00               6.00
mean          2.50            895.00            149.00             223.75
std           1.87            181.41             41.80              45.35
min           0.00            533.00             65.00             133.25
25%           1.25            923.25            157.75             230.81
50%           2.50            948.50            161.50             237.12
75%           3.75            997.00            171.25             249.25
max           5.00           1012.00            175.00             253.00

In [156]:
df

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count
0,0,Copyright (c) InfoTeCS. All Rights Reserved ...,973,157,243.25
1,1,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",1005,174,251.25
2,2,"Аппаратные платформы HW2000 Q4, Q5 Модель Тип ...",924,160,231.00
3,3,Аппаратная платформа HW5000 Q1 Модель Тип Длин...,1012,175,253.00
4,4,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",923,163,230.75
5,5,"АО «ИнфоТеКС», 127083, Москва, улица Мишина, д...",533,65,133.25

In [15]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer(model_name_or_path="ai-forever/ru-en-RoSBERTa", 
                                      device="cuda") # choose the device to load the model to (note: GPU will often be *much* faster than CPU)

2026-01-28 06:57:09.747453: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Some weights of RobertaModel were not initialized from the model checkpoint at ai-forever/ru-en-RoSBERTa and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [157]:
pages_and_chunks = df.sentence_chunk

In [158]:
pages_and_chunks.tolist()

['Copyright (c) InfoTeCS. All Rights Reserved   Аппаратные платформы HW100 N1, N2, N3 Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Avago AFBR-5710PZ SFP 850 LC duplex MM 0,5 Allied Telesis AT-SPEX SFP 1310 LC duplex MM 2 FINISAR FTLX8574D3BCV SFP/SFP+ 850 LC duplex MM 0,4 FTLX8519P3BNL SFP 850 LC duplex MM 0,3 FTLF1318P3BTL SFP 1310 LC duplex SM 10 MlaxLink ML-P10G-03DFM-85LD SFP+ 850 LC duplex MM 0,3 ML-SG-01UTP-SGMRJ SFP - RJ-45 UTP 0,1 Smartoptics SO-SFP-10GE-T SFP+ - RJ-45 - 0,03 Аппаратная платформа HW100 Q1, Q2 Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Avago AFBR-5710PZ SFP 850 LC duplex MM 0,5 FINISAR FTLX8574D3BCV SFP/SFP+ 850 LC duplex MM 0,4 SNR SNR-SFP-W35-3-LC SFP 1310 SC simplex SM 3 Аппаратная платформа HW1000 Q6 Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Avago AFBR-5710PZ SFP 850 LC duplex MM 0,5 Allied Telesis ViPNet Coordinator HW 5 Перечень совместимых трансиверов Версия продукта 5.3.2',
 'Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км AT-SPEX SFP 1310 LC duplex MM 2 D-Link DEM-432XT/B1A SFP+ 1310 LC duplex SM 10 FINISAR FTLX8574D3BCV SFP/SFP + 850 LC duplex MM 0,4 FTLX8519P3BNL SFP 850 LC duplex MM 0,3 FTLF1318P3BTL SFP 1310 LC duplex SM 10 Аппаратная платформа HW1000 Q9 Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Avago AFBR-5710PZ SFP 850 LC duplex MM 0,5 Allied Telesis AT-SPEX SFP 1310 LC duplex MM 2 Fang Hang FH-S8512CDL05 SFP 850 LC MM 0,55 FINISAR FTLX8574D3BCV SFP/SFP+ 850 LC duplex MM 0,4 FTLX8519P3BNL SFP 850 LC duplex MM 0,3 FTLF1318P3BTL SFP 1310 LC duplex SM 10 FS. COM SFP1G-SX-85 SFP 850 LC duplex MM 0,55 SFP-10GSR-85 SFP+ 850 LC duplex MM 0,3 HIRSCHMANN M-SFP-LX/LC SFP n/a LC duplex MM/SM 0,55 / 25 RBT12SLX-IT3 SFP 1310 LC single MM/SM 0,55 / 25 RBT12SLX-IT5 SFP 1550 LC single MM/SM 0,55 / 25 MlaxLink ML-P10G-03DFM-85LD SFP+ 850 LC duplex MM 0,3 ML-SG-01UTP-SGMRJ SFP - RJ-45 UTP 0,1 Smartoptics SO-SFP-10GE-T SFP+ - RJ-45 - 0,03',
 'Аппаратные платформы HW2000 Q4, Q5 Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Avago AFBR-709SMZ SFP+ 850 LC duplex MM 0,4 AFBR-710SMZ SFP+ 850 LC duplex MM 0,4 Allied Telesis AT-SPEX SFP 1310 LC duplex MM 2 Cisco Cisco SFP-10G-SR SFP+ 850 LC duplex MM 0,4 D-Link DEM-432XT/B1A SFP+ 1310 LC duplex SM 10 FINISAR FTLX8574D3BCV SFP/SFP+ 850 LC duplex MM 0,4 FTLF1318P3BTL SFP 1310 LC duplex SM 10 FTLX1475D3BCL SFP+ 1310 LC duplex SM 10 HUAWEI 02311RLX SFP+ 1310 LC duplex SM 40 OSX010000 SFP+ 1310 LC duplex SM 10 OSX010N05 SFP+ 1310 LC SM 10 Intel FTLX8574D3BCV-IT SFP+ 850 LC duplex MM 0,3 FTLX1471D3BCV-IT SFP+ 1310 LC duplex SM 10 LR-LINK LRXP8510-X3ATL SFP+ 850 LC duplex MM 0,3 MikroTik S+85DLC03D SFP+ 850 LC duplex MM 0,3 S+31DLC10D SFP+ 1310 LC duplex SM 10 MlaxLink ML-P10G-03DFM-85LD SFP+ 850 LC duplex MM 0,3 ML-SG-01UTP-SGMRJ SFP - RJ-45 UTP 0,1 ZYXEL ZYXEL SFP10G-SR SFP+ 850 LC duplex MM 0,3',
 'Аппаратная платформа HW5000 Q1 Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Avago AFBR-709SMZ SFP+ 850 LC duplex MM 0,4 AFBR-710SMZ SFP+ 850 LC duplex MM 0,4 Allied Telesis AT-SPEX SFP 1310 LC duplex MM 2 Cisco Cisco SFP-10G-SR SFP+ 850 LC duplex MM 0,4 D-Link DEM-432XT/B1A SFP+ 1310 LC duplex SM 10 FINISAR FTLX8574D3BCV SFP/SFP+ 850 LC duplex MM 0,4 FTLF1318P3BTL SFP 1310 LC duplex SM 10 FTLX1475D3BCL SFP+ 1310 LC duplex SM 10 HUAWEI 02311RLX SFP+ 1310 LC duplex SM 40 OSX010000 SFP+ 1310 LC duplex SM 10 Intel FTLX8574D3BCV-IT SFP+ 850 LC duplex MM 0,3 FTLX1471D3BCV-IT SFP+ 1310 LC duplex SM 10 LR-LINK LRXP8510-X3ATL SFP+ 850 LC duplex MM 0,3 MikroTik S+85DLC03D SFP+ 850 LC duplex MM 0,3 S+31DLC10D SFP+ 1310 LC duplex SM 10 ZYXEL ZYXEL SFP10G-SR SFP+ 850 LC duplex MM 0,3 Аппаратная платформа HW5000 Q2 Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Avago AFBR-5710PZ SFP 850 LC duplex MM 0,5 AFBR-709SMZ SFP+ 850 LC duplex MM 0,4 AFBR-710SMZ SFP+ 850 LC duplex MM 0,4',
 'Модель Тип Длина волны, нм Интерфейс Тип кабеля Расстояние, км Allied Telesis AT-SPEX SFP 1310 LC duplex MM 2 Cisco Cisco SFP-10G-SR SFP+ 850 LC duplex MM 0,4 D-Link DEM-432XT/B1A SFP+ 1310 LC duplex SM 10 FINISAR FTLX8574D3BCV SFP/SFP+ 850 LC duplex MM 0,4 FTLF1318P3BTL SFP 1310 LC duplex SM 10 FTLX1475D3BCL SFP+ 1310 LC duplex SM 10 FS. COM SFP1G-SX-85 SFP 850 LC duplex MM 0,55 SFP-10GSR-85 SFP+ 850 LC duplex MM 0,3 HUAWEI 02311RLX SFP+ 1310 LC duplex SM 40 OSX010000 SFP+ 1310 LC duplex SM 10 OSX010N05 SFP+ 1310 LC SM 10 SFP-1000BaseT SFP+ - RJ-45 - 0,1 Intel FTLX1471D3BCV-IT SFP+ 1310 LC duplex SM 10 LR-LINK LRXP8510-X3ATL SFP+ 850 LC duplex MM 0,3 MikroTik S+85DLC03D SFP+ 850 LC duplex MM 0,3 S+31DLC10D SFP+ 1310 LC duplex SM 10 MlaxLink ML-P10G-03DFM-85LD SFP+ 850 LC duplex MM 0,3 ML-SG-01UTP-SGMRJ SFP - RJ-45 UTP 0,1 SNR SNR-SFP+SR SFP+ 850 LC duplex MM 0,3 ZYXEL ZYXEL SFP10G-SR SFP+ 850 LC duplex MM 0,3',
 'АО «ИнфоТеКС», 127083, Москва, улица Мишина, д. 56, стр. 2, этаж 2, помещение IX, комната 29 Телефон: +7 (495) 737-6192, 8 (800) 250-0260 — бесплатный звонок из России (кроме Москвы) Сайт: infotecs.ru Служба поддержки: hotline@infotecs.ru, телеграм-канал поддержки: t.me/vhd21 ФРКЕ.465614.003ИС7, версия продукта 5.3.2 © АО «ИнфоТеКС», 2024. ViPNet® является зарегистрированным товарным знаком АО «ИнфоТеКС». Все названия компаний и продуктов, являющиеся зарегистрированными товарными знаками, принадлежат соответствующим владельцам.']

In [159]:
text_chunk_embeddings=[]
for i in pages_and_chunks.tolist():
    text_chunk_embeddings.append(embedding_model.encode(i,
                                               batch_size=32, # you can use different batch sizes here for speed/performance, I found 32 works well for this use case
                                               convert_to_tensor=True))

In [160]:
text_chunk_embeddings

[tensor([ 0.0042, -0.0040,  0.0231,  ...,  0.0195, -0.0190, -0.0074],
        device='cuda:0'),
 tensor([-0.0147,  0.0232,  0.0069,  ...,  0.0107, -0.0097, -0.0114],
        device='cuda:0'),
 tensor([ 0.0024,  0.0181,  0.0194,  ...,  0.0186, -0.0066, -0.0167],
        device='cuda:0'),
 tensor([ 0.0007,  0.0152,  0.0219,  ...,  0.0185, -0.0009, -0.0157],
        device='cuda:0'),
 tensor([-2.3185e-03,  1.3453e-02,  2.1185e-02,  ...,  1.7644e-02,
         -6.6569e-05, -1.6092e-02], device='cuda:0'),
 tensor([-0.0109, -0.0332,  0.0499,  ...,  0.0034,  0.0307, -0.0284],
        device='cuda:0')]

In [161]:
text_chunk_embeddings_list = []
for i in text_chunk_embeddings:
    text_chunk_embeddings_list.append(i.tolist())

In [162]:
text_chunk_embeddings_list

[[0.004246750380843878,
  -0.003971358295530081,
  0.02313687652349472,
  0.01397034339606762,
  -0.006961638107895851,
  0.013670289888978004,
  0.026896491646766663,
  0.0075852712616324425,
  0.022998834028840065,
  0.008264067582786083,
  0.012624431401491165,
  -0.0005829408764839172,
  0.013871158473193645,
  -0.03723147511482239,
  -0.020602280274033546,
  0.06948986649513245,
  -0.03298730403184891,
  -0.033339500427246094,
  -0.012561855837702751,
  -0.021445589140057564,
  -0.0014110993361100554,
  0.03477207571268082,
  0.01993366703391075,
  0.03633282706141472,
  0.01824379526078701,
  0.01754799857735634,
  -0.012471224181354046,
  -0.033341292291879654,
  -0.0024051533546298742,
  0.015582953579723835,
  0.001729471143335104,
  0.014078963547945023,
  0.00159259676001966,
  -0.0017826429102569818,
  0.010386661626398563,
  0.0149122579023242,
  -0.02265290915966034,
  0.003797390731051564,
  -0.028591757640242577,
  -0.011390988714993,
  -0.06350996345281601,
  -0.01826922968029976,
  -0.00203261012211442,
  -0.016936805099248886,
  -0.0008648353978060186,
  -0.0005944529548287392,
  0.011345969513058662,
  0.04728727415204048,
  0.009857069700956345,
  0.00975917000323534,
  -0.005299804266542196,
  0.038578812032938004,
  -0.006640979554504156,
  0.0026158634573221207,
  -0.0195707269012928,
  -0.01631229743361473,
  0.0015935238916426897,
  0.008937320671975613,
  0.025287993252277374,
  -0.030148493126034737,
  -0.03621586784720421,
  -0.013092292472720146,
  -0.02668282948434353,
  -0.09679123014211655,
  -0.05100621283054352,
  -0.041189420968294144,
  0.0103749455884099,
  -0.011835681274533272,
  0.01098078116774559,
  0.008137388154864311,
  0.013242237269878387,
  0.012206034734845161,
  0.0007355284760706127,
  -0.06540621072053909,
  0.042924392968416214,
  -0.03292714059352875,
  0.028477070853114128,
  0.0023481626994907856,
  -0.023914054036140442,
  0.0026123335119336843,
  0.00987222883850336,
  0.011567365378141403,
  -0.015117222443223,
  0.0003440996224526316,
  0.02429174818098545,
  0.005893925670534372,
  0.021987566724419594,
  0.02062244899570942,
  0.03792236000299454,
  0.03868957981467247,
  -0.04320406913757324,
  -0.033127203583717346,
  0.00659460574388504,
  0.023581409826874733,
  -0.003224910469725728,
  0.021783078089356422,
  -0.015528467483818531,
  0.041145846247673035,
  -0.049790315330028534,
  -0.02292877808213234,
  0.015004820190370083,
  0.025378158316016197,
  0.061484385281801224,
  -0.031689081341028214,
  -0.018689043819904327,
  -0.02280639298260212,
  0.031624067574739456,
  0.025639858096837997,
  0.004828235134482384,
  0.01704474724829197,
  -0.0006981284823268652,
  -0.0066172461956739426,
  -0.020348571240901947,
  -0.01285592932254076,
  -0.037213392555713654,
  0.030135566368699074,
  -0.0026030121371150017,
  -0.03278060629963875,
  -0.04251021891832352,
  0.003311079228296876,
  -0.020273763686418533,
  -0.002044584369286895,
  0.007879247888922691,
  -0.0033427164889872074,
  -0.008161447010934353,
  0.03006388619542122,
  -0.035747114568948746,
  -0.017137395218014717,
  0.0009606269304640591,
  0.021493952721357346,
  0.017610033974051476,
  0.004631816875189543,
  -0.023258784785866737,
  -0.01160319335758686,
  0.01821596547961235,
  -0.03569426387548447,
  0.01621049828827381,
  0.012770640663802624,
  -0.020812980830669403,
  -0.026275429874658585,
  0.02538207173347473,
  0.017682531848549843,
  0.00018978795560542494,
  -0.012793764472007751,
  0.017999926581978798,
  -0.025278940796852112,
  -0.00040573670412413776,
  0.001664794166572392,
  -0.01298614777624607,
  0.038037508726119995,
  0.01001204177737236,
  0.0520302839577198,
  -0.009042729623615742,
  -0.007381876464933157,
  0.02527981996536255,
  0.005166014656424522,
  0.0018667096737772226,
  0.0007352491957135499,
  -0.007549656089395285,
  0.0036335678305476904,
  0.02315511927008629,
  0.014783119782805443,
  -0.015259671956300735,
  -0.0020358662586659193,
  -0.011043265461921692,
  0.030141126364469528,
  -0.019248012453317642,
  0.026559647172689438,
  -0.0005017219227738678,
  -0.027431031689047813,
  0.0034519522450864315,
  0.03080076538026333,
  -0.03593294695019722,
  0.07096253335475922,
  -0.015902210026979446,
  -0.0068814074620604515,
  0.051191121339797974,
  -0.005601221229881048,
  -0.0044730412773787975,
  -0.03676784411072731,
  -0.019832374528050423,
  -0.0021453509107232094,
  0.08504936099052429,
  -0.018693016842007637,
  0.03089466132223606,
  -0.00560637516900897,
  0.011415655724704266,
  0.030415020883083344,
  -0.02338149957358837,
  0.04969136416912079,
  0.023500844836235046,
  -0.019820012152194977,
  -0.05182052403688431,
  -0.020589618012309074,
  0.007795917801558971,
  0.015218803659081459,
  -0.03649960085749626,
  0.01683376170694828,
  -0.00794137828052044,
  0.05529535934329033,
  0.014086438342928886,
  0.03753238543868065,
  -0.03301135450601578,
  0.02842891961336136,
  0.017847616225481033,
  -0.0335480272769928,
  -0.03664557635784149,
  0.0008258649031631649,
  0.009262221865355968,
  0.019552823156118393,
  -0.034190114587545395,
  -0.013667413033545017,
  0.025808095932006836,
  -0.03846322372555733,
  0.031161706894636154,
  0.0006409416673704982,
  0.013523436151444912,
  0.01896406151354313,
  -0.004114416893571615,
  -0.039821822196245193,
  0.026152625679969788,
  -0.014860454015433788,
  0.03777192533016205,
  -0.038098257035017014,
  0.0313238799571991,
  -0.006900319829583168,
  0.028469210490584373,
  -0.0027299239300191402,
  0.005413232836872339,
  -0.013017107732594013,
  -0.03697273135185242,
  -0.01982440985739231,
  0.025341574102640152,
  0.01740914024412632,
  -0.01130798738449812,
  0.047038283199071884,
  -0.005803762003779411,
  -0.04285841062664986,
  -0.0012898124987259507,
  0.020471617579460144,
  0.009307227097451687,
  0.026330778375267982,
  0.046726785600185394,
  -0.0429646298289299,
  0.032945603132247925,
  0.03298657014966011,
  -0.00869840756058693,
  0.016808591783046722,
  -0.00618043914437294,
  0.027943694964051247,
  -0.0363026037812233,
  0.001349907019175589,
  -0.005645018070936203,
  -0.002130359411239624,
  0.006168108433485031,
  0.02587125264108181,
  -0.006268246099352837,
  0.021939340978860855,
  0.0015616047894582152,
  -0.020388009026646614,
  0.01072321180254221,
  0.0002929308102466166,
  0.015270714648067951,
  0.013987062498927116,
  -0.005192663986235857,
  -0.06548109650611877,
  0.012436583638191223,
  -0.025796402245759964,
  -0.016036134213209152,
  0.0027089896611869335,
  0.04181799292564392,
  0.0432487428188324,
  0.007296009920537472,
  -0.0010752608068287373,
  -0.044833529740571976,
  0.018224120140075684,
  0.007198486011475325,
  0.024623187258839607,
  -0.004647769033908844,
  0.008801918476819992,
  -0.016868632286787033,
  -0.038394562900066376,
  0.02829698845744133,
  -0.0070016151294112206,
  0.015345062129199505,
  0.004119666758924723,
  0.006082957144826651,
  0.02083646133542061,
  -0.010735363699495792,
  -0.0016374543774873018,
  0.0010964166140183806,
  -0.015184853225946426,
  0.01055995188653469,
  0.013730796054005623,
  0.015107347629964352,
  0.006316517945379019,
  -0.042770251631736755,
  -0.024904999881982803,
  -0.02941911108791828,
  0.0021589635871350765,
  0.058472853153944016,
  -0.013195784762501717,
  -0.01947232522070408,
  0.014725690707564354,
  -0.010071070864796638,
  0.0215457770973444,
  -0.025612343102693558,
  0.005857132375240326,
  0.007654225453734398,
  -0.03632725402712822,
  0.05090627819299698,
  -0.0317668691277504,
  0.020245753228664398,
  -0.07637102901935577,
  0.05009855702519417,
  -0.03765103593468666,
  -0.03673969581723213,
  -0.007485655602067709,
  0.019266024231910706,
  0.013058740645647049,
  0.004140954464673996,
  -0.008610573597252369,
  0.03238164260983467,
  -0.01723218522965908,
  6.25454995315522e-05,
  0.014604872092604637,
  0.03887027129530907,
  -0.02530786208808422,
  -0.030958160758018494,
  -0.029936620965600014,
  0.029554132372140884,
  0.03455096855759621,
  0.016829045489430428,
  0.018849259242415428,
  -0.0585978664457798,
  0.014737810008227825,
  0.015527267009019852,
  -0.00681401789188385,
  0.012807236053049564,
  0.029753968119621277,
  0.008968851529061794,
  0.048425570130348206,
  0.012993172742426395,
  0.00789070874452591,
  0.01943528838455677,
  -0.004749653395265341,
  -0.019066568464040756,
  -0.0021448356565088034,
  -0.0516725555062294,
  -0.02398758940398693,
  0.0029465912375599146,
  -0.007956947200000286,
  0.021881185472011566,
  0.011217840947210789,
  -0.006602201610803604,
  0.02154122292995453,
  0.011614530347287655,
  -0.018496515229344368,
  -0.009488237090408802,
  -0.015023707412183285,
  -0.004258974455296993,
  0.019080501049757004,
  0.007956703193485737,
  0.0432741679251194,
  0.018680300563573837,
  -0.028398476541042328,
  -0.006361181382089853,
  -0.01105357613414526,
  -0.020324712619185448,
  0.004099979531019926,
  -0.03203362599015236,
  0.0016098673222586513,
  0.0002345757238799706,
  -0.02107679285109043,
  -0.019241224974393845,
  0.0007292006630450487,
  -0.017055895179510117,
  -0.006607588846236467,
  0.0016291603678837419,
  -0.010839449241757393,
  -0.012299918569624424,
  -0.02365056611597538,
  -0.021784484386444092,
  -0.00619408069178462,
  -0.019424142315983772,
  -0.01802872307598591,
  0.013892143033444881,
  0.0072088888846337795,
  -0.012907728552818298,
  -0.00568628404289484,
  0.014362122863531113,
  -0.001027324702590704,
  -0.0256037674844265,
  0.019647641107439995,
  -0.0022826045751571655,
  -0.011886999942362309,
  -0.013230192475020885,
  0.023430127650499344,
  -0.02325291372835636,
  -0.009145518764853477,
  -0.009877079166471958,
  -0.015285637229681015,
  -0.015160879120230675,
  -0.050821881741285324,
  0.024542249739170074,
  0.02372351661324501,
  -0.006017683539539576,
  0.012109484523534775,
  -0.06777063012123108,
  0.009947116486728191,
  0.049562662839889526,
  -0.011807757429778576,
  0.02898572012782097,
  0.008973239921033382,
  -0.005245399195700884,
  0.07031068950891495,
  0.014194834977388382,
  -0.018806975334882736,
  0.002986149163916707,
  0.044335074722766876,
  0.04104398563504219,
  0.006401374004781246,
  -0.008113695308566093,
  0.04045592620968819,
  -0.004813179839402437,
  -0.03865667060017586,
  -0.002423918107524514,
  -0.027707504108548164,
  0.0642043948173523,
  0.01732061244547367,
  -0.0027897614054381847,
  -0.03863693028688431,
  -0.02011430636048317,
  0.038643304258584976,
  0.02348516881465912,
  -0.056493502110242844,
  -0.008375898003578186,
  0.0005867229774594307,
  -0.02240184135735035,
  0.0013954065507277846,
  0.049641478806734085,
  -0.0523177869617939,
  0.011185016483068466,
  0.028851106762886047,
  0.01112933736294508,
  -0.01821606419980526,
  -0.01464362908154726,
  -0.033890701830387115,
  -0.017757976427674294,
  0.04997016116976738,
  -0.014480012468993664,
  0.0022821587044745684,
  -0.024216877296566963,
  0.006811848841607571,
  0.017848918214440346,
  -0.006178523413836956,
  0.0137016661465168,
  -0.010385779663920403,
  -0.012990721501410007,
  0.013202625326812267,
  0.015228915959596634,
  0.021218322217464447,
  0.01637347787618637,
  0.02512575313448906,
  -0.06384707987308502,
  -0.04025019705295563,
  -0.013796495273709297,
  0.03983759507536888,
  -0.032728370279073715,
  -0.013974190689623356,
  0.0008531141793355346,
  -0.011176986619830132,
  0.013435754925012589,
  0.0008641059976071119,
  -0.010915794409811497,
  -0.01585514470934868,
  -0.06029141694307327,
  -0.0012181884376332164,
  0.020119234919548035,
  0.013588879257440567,
  -0.006452560890465975,
  -0.03414620831608772,
  -0.0758376270532608,
  0.04725215211510658,
  -0.03975122794508934,
  -0.015235405415296555,
  0.03802523761987686,
  -0.007673410698771477,
  0.015841547399759293,
  0.022583890706300735,
  -0.017465580254793167,
  -0.007839946076273918,
  0.029309045523405075,
  -0.022615494206547737,
  -0.01964896358549595,
  0.03307322785258293,
  0.012538141570985317,
  -0.010739271529018879,
  -0.016749029979109764,
  -0.02980542927980423,
  0.0134891327470541,
  0.020625364035367966,
  0.02177121490240097,
  -0.02218378707766533,
  0.019737986847758293,
  -0.021291913464665413,
  -0.009428814053535461,
  -0.019360696896910667,
  0.016670722514390945,
  -0.006872228346765041,
  0.005598125513643026,
  -0.03636918589472771,
  0.03072088584303856,
  0.013743046671152115,
  -0.01233858335763216,
  -0.022449398413300514,
  -0.01591925136744976,
  -0.035179316997528076,
  0.040957801043987274,
  0.043973542749881744,
  -0.009257018566131592,
  0.00786005798727274,
  -0.02546697109937668,
  0.016368497163057327,
  0.00462523614987731,
  -0.010104517452418804,
  -0.019525302574038506,
  0.01775679551064968,
  -0.025344038382172585,
  0.015797270461916924,
  0.013034910894930363,
  -0.0008130250498652458,
  -0.01782885007560253,
  -0.007515231147408485,
  -0.007036510389298201,
  -0.027454689145088196,
  -0.035383909940719604,
  -0.00934626068919897,
  0.008572328835725784,
  -0.0254227165132761,
  -0.013571543619036674,
  -0.041310977190732956,
  -0.05152703821659088,
  0.01155408937484026,
  -0.01584775187075138,
  0.025543635711073875,
  0.03236907348036766,
  7.423863280564547e-05,
  0.0035279160365462303,
  -0.012375757098197937,
  -0.016324901953339577,
  -0.021914595738053322,
  0.05168480798602104,
  -0.024870479479432106,
  0.009683944284915924,
  -0.002442802069708705,
  -0.02916116826236248,
  -0.05391646549105644,
  -0.025060154497623444,
  0.02669120952486992,
  -0.022027473896741867,
  -0.014005327597260475,
  -0.005646728910505772,
  -0.0022360871080309153,
  -0.029880033805966377,
  0.066104955971241,
  0.03569089248776436,
  0.0003805705637205392,
  0.038470808416604996,
  -0.021366190165281296,
  0.029279327020049095,
  -0.5003602504730225,
  0.04927926883101463,
  0.018155334517359734,
  0.030892156064510345,
  -0.005979286972433329,
  -0.0032071617897599936,
  -0.011036629788577557,
  -0.045899584889411926,
  -0.0431571789085865,
  0.00351275154389441,
  0.0007143450784496963,
  -0.006808203179389238,
  -0.0003548853856045753,
  -0.020849380642175674,
  -0.006394992582499981,
  0.03467750549316406,
  -0.006036214530467987,
  -0.017977537587285042,
  -0.04052744433283806,
  -0.015200155787169933,
  0.013848142698407173,
  0.0008101480198092759,
  -0.04365174099802971,
  -0.0014943797141313553,
  -0.004496103152632713,
  -0.020939692854881287,
  -0.018621446564793587,
  0.08827251195907593,
  -0.011223841458559036,
  -0.060016606003046036,
  0.02273147739470005,
  0.0259631909430027,
  0.016293659806251526,
  0.01506587490439415,
  -0.01509456243366003,
  0.01914357766509056,
  0.005205634981393814,
  -0.012085214257240295,
  0.04503273591399193,
  0.02535688318312168,
  0.043193694204092026,
  0.05224744975566864,
  -0.01119502168148756,
  -0.019992684945464134,
  0.028579387813806534,
  -0.022606845945119858,
  -0.0005786072579212487,
  -0.010479399003088474,
  0.024051211774349213,
  0.057204101234674454,
  0.03681299835443497,
  -0.016652865335345268,
  0.00677018566057086,
  0.020276442170143127,
  0.018570981919765472,
  0.0029010844882577658,
  -0.012569795362651348,
  0.003928867634385824,
  -0.008180038072168827,
  -0.03325330838561058,
  0.05252208188176155,
  0.019075030460953712,
  0.0019315991085022688,
  0.00285336677916348,
  0.04774327203631401,
  0.021094409748911858,
  -0.025209471583366394,
  0.001335485721938312,
  -0.030205056071281433,
  -0.02659769356250763,
  0.032091543078422546,
  -0.02659703604876995,
  0.02355191484093666,
  0.04407859593629837,
  -0.004860818851739168,
  0.03345167264342308,
  -0.012983064167201519,
  -0.022436797618865967,
  0.005096177104860544,
  -0.008349672891199589,
  0.03146102651953697,
  0.024038976058363914,
  -0.04124480485916138,
  0.016001373529434204,
  -0.02599862962961197,
  0.016620879992842674,
  0.048394087702035904,
  -0.01760018989443779,
  0.0003144405491184443,
  -0.006932827178388834,
  0.021842509508132935,
  -0.0470479354262352,
  -0.006697812117636204,
  0.013595068827271461,
  -0.002601361833512783,
  -0.020392946898937225,
  0.02059963531792164,
  -0.00736090075224638,
  -0.01723407581448555,
  0.0029618560802191496,
  0.05650373175740242,
  0.007135390304028988,
  0.0004972325987182558,
  0.004595720209181309,
  0.033715102821588516,
  -0.013886458240449429,
  0.0021603391505777836,
  -0.01547170989215374,
  0.0023807769175618887,
  0.0007668716134503484,
  0.05700797960162163,
  -0.005865441169589758,
  0.028510522097349167,
  -0.002686810214072466,
  -0.004292940255254507,
  0.03735874220728874,
  0.0741407573223114,
  0.0223013237118721,
  0.002405542181804776,
  -0.004152235109359026,
  -0.002211047103628516,
  0.004287191666662693,
  -0.015774782747030258,
  0.01407091785222292,
  -0.0158949363976717,
  -0.013434253633022308,
  -0.05146011710166931,
  -0.03380543366074562,
  -0.04811996594071388,
  -0.023188192397356033,
  0.04225246608257294,
  -0.042736150324344635,
  0.011194121092557907,
  0.02310396172106266,
  0.00542021170258522,
  -0.015527794137597084,
  0.0321924090385437,
  0.0055712866596877575,
  -0.026885313913226128,
  -0.04038681834936142,
  0.030653662979602814,
  0.02320719324052334,
  -0.023756662383675575,
  0.03514173626899719,
  -0.053296104073524475,
  -0.0636972039937973,
  -0.007923995144665241,
  -0.022378236055374146,
  -0.04369929060339928,
  0.011827964335680008,
  0.036571960896253586,
  -0.009361793287098408,
  -0.0014170692302286625,
  -0.03586110100150108,
  0.028812384232878685,
  -0.04622267931699753,
  -0.04367394372820854,
  0.0022427074145525694,
  -0.011059817858040333,
  -0.020688576623797417,
  0.002191647421568632,
  0.026378409937024117,
  -0.027153147384524345,
  0.013569345697760582,
  0.004061644896864891,
  -0.051421262323856354,
  0.05082574486732483,
  -0.019057417288422585,
  0.012077604420483112,
  0.016823820769786835,
  -0.009760269895195961,
  -0.004102486651390791,
  0.023503350093960762,
  0.032230738550424576,
  -0.06595350056886673,
  -0.0032121543772518635,
  -0.007625879719853401,
  0.03327815979719162,
  -0.0060754441656172276,
  0.009755571372807026,
  0.012081875465810299,
  0.01727423258125782,
  0.057685736566782,
  -0.05313682556152344,
  0.04391665384173393,
  -0.022944234311580658,
  -0.007045204751193523,
  -0.009481208398938179,
  0.022986778989434242,
  -0.03750765323638916,
  0.020329415798187256,
  0.018878061324357986,
  0.010032144375145435,
  0.011844060383737087,
  -0.013998164795339108,
  -0.006866443902254105,
  0.009905817918479443,
  -0.033651672303676605,
  0.00929967314004898,
  -0.03223126754164696,
  0.015979433432221413,
  0.006679939106106758,
  -0.018963903188705444,
  0.0158145222812891,
  -0.013319797813892365,
  -0.03492499887943268,
  -0.050327956676483154,
  0.0157968420535326,
  -0.015563417226076126,
  -0.0005456169019453228,
  -0.006021869834512472,
  0.015296676196157932,
  -0.04976312443614006,
  0.016684796661138535,
  0.04034297913312912,
  -0.013135873712599277,
  -0.018388869240880013,
  0.03552524000406265,
  -0.0010648720199242234,
  0.021555092185735703,
  -0.03301088511943817,
  -0.0031167427077889442,
  0.04077411815524101,
  0.013945856131613255,
  0.05664857104420662,
  -0.020861517637968063,
  -0.01986599713563919,
  0.0016635230276733637,
  -0.011187203228473663,
  -0.001350145204924047,
  0.050381891429424286,
  0.015747785568237305,
  -0.018197258934378624,
  0.007921196520328522,
  -0.0048306891694664955,
  -0.006655614823102951,
  -0.030057769268751144,
  0.023885641247034073,
  0.008417166769504547,
  -0.033184800297021866,
  0.036568835377693176,
  -0.009106004610657692,
  0.014258043840527534,
  0.003851998597383499,
  -0.023494793102145195,
  0.0019817559514194727,
  -0.030965130776166916,
  -0.0020362497307360172,
  -0.020957650616765022,
  0.0143594266846776,
  0.014626584015786648,
  0.0013687877217307687,
  0.011596760712563992,
  0.040665462613105774,

In [163]:
df['embedding'] = text_chunk_embeddings_list
df

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,0,Copyright (c) InfoTeCS. All Rights Reserved ...,973,157,243.25,"[0.004246750380843878, -0.003971358295530081, ..."
1,1,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",1005,174,251.25,"[-0.014727634377777576, 0.023174844682216644, ..."
2,2,"Аппаратные платформы HW2000 Q4, Q5 Модель Тип ...",924,160,231.00,"[0.0024295246694236994, 0.018062317743897438, ..."
3,3,Аппаратная платформа HW5000 Q1 Модель Тип Длин...,1012,175,253.00,"[0.0006676093325950205, 0.015232657082378864, ..."
4,4,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",923,163,230.75,"[-0.0023184509482234716, 0.013453398831188679,..."
5,5,"АО «ИнфоТеКС», 127083, Москва, улица Мишина, д...",533,65,133.25,"[-0.010863716714084148, -0.03315876051783562, ..."

In [164]:
# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(df)
embeddings_df_save_path = "07_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

In [165]:
df7 =df

In [167]:
df1['product']='подготовка'
df1

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
16,1,ViPNet Coordinator HW 5.Подготовка к работе | ...,1274,159,318.50,"[0.0060768756084144115, -0.042224615812301636,...",подготовка
17,1,NAT позволяет решить две задачи:  Подключение...,930,112,232.50,"[-0.007902384735643864, -0.02230028621852398, ...",подготовка
18,2,ViPNet Coordinator HW 5.Подготовка к работе | ...,234,35,58.50,"[0.008719977922737598, -0.03479960188269615, -...",подготовка
19,3,ViPNet Coordinator HW 5.Подготовка к работе | ...,1222,149,305.50,"[-0.022762130945920944, -0.0357675738632679, 0...",подготовка
20,3,Событие срабатывания правила IPS регистрируетс...,314,43,78.50,"[-0.017361363396048546, 0.0026617932599037886,...",подготовка
...,...,...,...,...,...,...,...
150,82,В ViPNet Coordinator HW версии 5.0 и выше испо...,972,125,243.00,"[-0.010205193422734737, -0.04487336426973343, ...",подготовка
151,83,ViPNet Coordinator HW 5.Подготовка к работе | ...,1153,138,288.25,"[-0.00508173368871212, -0.054079338908195496, ...",подготовка
152,83,"Сеть ViPNet Логическая сеть, организованная с ...",484,59,121.00,"[0.011589154601097107, -0.03198278695344925, 0...",подготовка
153,84,ViPNet Coordinator HW 5.Подготовка к работе | ...,1197,140,299.25,"[-0.010457828640937805, -0.030137909576296806,...",подготовка
154,84,Шлюзовые координаторы назначаются в ViPNet Pri...,129,16,32.25,"[-0.005009430460631847, -0.046057138592004776,...",подготовка

In [169]:
df2['product']='cli'
df2

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
21,1,ViPNet Coordinator HW 5.Настройка с помощью ко...,1501,194,375.25,"[0.005142953246831894, -0.011179185472428799, ...",cli
22,1,Контекстная справка вызывается с помощью симво...,51,7,12.75,"[-0.0031007288489490747, 0.03535120561718941, ...",cli
23,2,ViPNet Coordinator HW 5.Настройка с помощью ко...,1501,228,375.25,"[-0.013882667757570744, -0.021430110558867455,...",cli
24,3,ViPNet Coordinator HW 5.Настройка с помощью ко...,783,115,195.75,"[0.0022246644366532564, 0.007002372294664383, ...",cli
25,4,ViPNet Coordinator HW 5.Настройка с помощью ко...,662,104,165.50,"[-0.003028304548934102, -0.003923141397535801,...",cli
...,...,...,...,...,...,...,...
709,459,ViPNet Coordinator HW 5.Настройка с помощью ко...,1381,167,345.25,"[-0.015024119056761265, -0.03959723562002182, ...",cli
710,459,В сети ViPNet-координатор выполняет серверные ...,416,43,104.00,"[0.008524478413164616, -0.0642639696598053, 0....",cli
711,460,ViPNet Coordinator HW 5.Настройка с помощью ко...,1102,135,275.50,"[0.0068259150721132755, -0.04547770693898201, ...",cli
712,460,"Сеть ViPNet имеет наложенную маршрутизацию, об...",466,54,116.50,"[-0.004009568132460117, -0.026541519910097122,...",cli
713,461,ViPNet Coordinator HW 5.Настройка с помощью ко...,1184,134,296.00,"[-0.030780218541622162, -0.04356885328888893, ...",cli

In [170]:
df3['product']='web'
df3

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
15,1,ViPNet Coordinator HW 5.Настройка с помощью ве...,1247,158,311.75,"[-0.005449722986668348, -0.018273696303367615,...",web
16,1,o Для централизованной учётной записи нажмите ...,128,20,32.00,"[-0.05698039382696152, -0.0065096342004835606,...",web
17,2,ViPNet Coordinator HW 5.Настройка с помощью ве...,789,104,197.25,"[-0.01740676537156105, -0.021096395328640938, ...",web
18,2,3.4 Нажмите Войти. Примечание. USB-токен долж...,477,63,119.25,"[-0.023216310888528824, 0.05547713860869408, -...",web
19,3,ViPNet Coordinator HW 5.Настройка с помощью ве...,996,124,249.00,"[0.008452839218080044, -0.0075549413450062275,...",web
...,...,...,...,...,...,...,...
524,333,ViPNet Coordinator HW 5.Настройка с помощью ве...,1092,130,273.00,"[-0.0026286784559488297, -0.03871087729930878,...",web
525,333,Открытый трафик Поток незашифрованных IP-пакет...,393,52,98.25,"[-0.0017361302161589265, -0.04960127919912338,...",web
526,334,ViPNet Coordinator HW 5.Настройка с помощью ве...,1041,119,260.25,"[-0.006632652599364519, -0.042085472494363785,...",web
527,334,"Туннелируемый узел Узел, на котором не установ...",615,70,153.75,"[-0.014668844640254974, -0.06421870738267899, ...",web
528,335,ViPNet Coordinator HW 5.Настройка с помощью ве...,183,23,45.75,"[-0.0013466578675433993, -0.004676570184528828...",web

In [171]:
df4['product']='справочник'
df4

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
25,1,ViPNet Coordinator HW 5.Справочник команд и ко...,1076,134,269.00,"[-0.02569282427430153, -0.011641775257885456, ...",справочник
26,2,ViPNet Coordinator HW 5.Справочник команд и ко...,834,104,208.50,"[-0.01287016086280346, -0.0021392342168837786,...",справочник
27,2,Особенности использования  Значение счётчика ...,250,34,62.50,"[0.007124020252376795, 0.024593856185674667, -...",справочник
28,3,ViPNet Coordinator HW 5.Справочник команд и ко...,759,90,189.75,"[-0.009648045524954796, 0.01273731142282486, 0...",справочник
29,3,"В других сессиях пользователя, выполнившего ко...",668,100,167.00,"[-0.016790637746453285, 0.03096672147512436, -...",справочник
...,...,...,...,...,...,...,...
774,512,ViPNet Coordinator HW 5.Справочник команд и ко...,1188,135,297.00,"[0.003303920617327094, -0.034523844718933105, ...",справочник
775,512,Для организации взаимодействия между узлами ра...,446,50,111.50,"[0.006700849160552025, -0.011516018770635128, ...",справочник
776,513,ViPNet Coordinator HW 5.Справочник команд и ко...,980,122,245.00,"[0.00471540866419673, -0.05311654135584831, 0....",справочник
777,513,"Транспортная квитанция Файл, оповещающий отпра...",615,66,153.75,"[-0.027645885944366455, -0.015465979464352131,...",справочник
778,514,ViPNet Coordinator HW 5.Справочник команд и ко...,553,60,138.25,"[-0.016822075471282005, -0.04160011187195778, ...",справочник

In [172]:
df6['product']='история'
df6

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
0,0,Copyright (c) InfoTeCS. All Rights Reserved ...,1565,206,391.25,"[0.015076713636517525, -0.02475527487695217, 0...",история
1,1, Новое устройство аутентификации Рутокен ЭЦП ...,1686,206,421.50,"[-0.011273158714175224, 0.022998301312327385, ...",история
2,1,o В раздел Состояние системы веб-интерфейса до...,1033,142,258.25,"[0.0031716336961835623, -0.01651792600750923, ...",история
3,2, Изменение в настройке экспорта событий журна...,1504,202,376.00,"[-0.02878248319029808, -0.02799868956208229, 0...",история
4,3, iplir option set max-connections перенесены ...,1132,151,283.00,"[0.004034334793686867, -0.01688470132648945, 0...",история
5,3, Счетчики срабатывания правил межсетевого экр...,1105,136,276.25,"[0.00948849506676197, -0.006793113891035318, 0...",история
6,4, Новый журнал DNS-запросов Добавлен журнал DN...,1588,212,397.00,"[-0.000603150692768395, 0.008206577971577644, ...",история
7,4, Настройка туннелирования локальных адресов Д...,721,92,180.25,"[-0.02508709765970707, -0.018153706565499306, ...",история
8,5,запуска новых приложений.Также объем доступной...,1088,154,272.00,"[-3.625449608080089e-05, -0.035202719271183014...",история
9,5,o VMware vSphere ESXi и Workstation Pro. o Mic...,725,96,181.25,"[0.012960095889866352, 0.006272259168326855, 0...",история
10,6,Экспорт и импорт настроек универсальной конфиг...,1698,212,424.50,"[-0.01190020702779293, -0.004066783469170332, ...",история
11,6, Обновление базы правил IPS через прокси-серв...,1062,136,265.50,"[0.003870547516271472, -0.02486823871731758, 0...",история
12,7, Оповещение о скором истечении срока действия...,1970,310,492.50,"[-0.00790086667984724, -0.03616844490170479, 0...",история
13,7,Для обновления ПО с версий 4.5.х по-прежнему и...,86,12,21.50,"[0.0018097175052389503, -0.004795243963599205,...",история
14,8, Выбор профиля производительности Для исполне...,1611,204,402.75,"[0.021841662004590034, -0.011327165178954601, ...",история
15,8,События подсистемы предотвращения вторжений IP...,1113,136,278.25,"[0.007723822258412838, -0.05420991778373718, 0...",история
16,9, Администратор — пользователь с полномочиями ...,1313,171,328.25,"[0.0019302659202367067, -0.0335635244846344, 0...",история
17,9,Транспортный сервер MFTP работает в транзитном...,1264,164,316.00,"[0.003748262533918023, -0.04674435034394264, 0...",история

In [173]:
df7['product']='совместимость'
df7

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
0,0,Copyright (c) InfoTeCS. All Rights Reserved ...,973,157,243.25,"[0.004246750380843878, -0.003971358295530081, ...",совместимость
1,1,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",1005,174,251.25,"[-0.014727634377777576, 0.023174844682216644, ...",совместимость
2,2,"Аппаратные платформы HW2000 Q4, Q5 Модель Тип ...",924,160,231.00,"[0.0024295246694236994, 0.018062317743897438, ...",совместимость
3,3,Аппаратная платформа HW5000 Q1 Модель Тип Длин...,1012,175,253.00,"[0.0006676093325950205, 0.015232657082378864, ...",совместимость
4,4,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",923,163,230.75,"[-0.0023184509482234716, 0.013453398831188679,...",совместимость
5,5,"АО «ИнфоТеКС», 127083, Москва, улица Мишина, д...",533,65,133.25,"[-0.010863716714084148, -0.03315876051783562, ...",совместимость

In [175]:
dfi=pd.concat([df1,df2,df3,df4,df6,df7])
dfi

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
16,1,ViPNet Coordinator HW 5.Подготовка к работе | ...,1274,159,318.50,"[0.0060768756084144115, -0.042224615812301636,...",подготовка
17,1,NAT позволяет решить две задачи:  Подключение...,930,112,232.50,"[-0.007902384735643864, -0.02230028621852398, ...",подготовка
18,2,ViPNet Coordinator HW 5.Подготовка к работе | ...,234,35,58.50,"[0.008719977922737598, -0.03479960188269615, -...",подготовка
19,3,ViPNet Coordinator HW 5.Подготовка к работе | ...,1222,149,305.50,"[-0.022762130945920944, -0.0357675738632679, 0...",подготовка
20,3,Событие срабатывания правила IPS регистрируетс...,314,43,78.50,"[-0.017361363396048546, 0.0026617932599037886,...",подготовка
...,...,...,...,...,...,...,...
1,1,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",1005,174,251.25,"[-0.014727634377777576, 0.023174844682216644, ...",совместимость
2,2,"Аппаратные платформы HW2000 Q4, Q5 Модель Тип ...",924,160,231.00,"[0.0024295246694236994, 0.018062317743897438, ...",совместимость
3,3,Аппаратная платформа HW5000 Q1 Модель Тип Длин...,1012,175,253.00,"[0.0006676093325950205, 0.015232657082378864, ...",совместимость
4,4,"Модель Тип Длина волны, нм Интерфейс Тип кабел...",923,163,230.75,"[-0.0023184509482234716, 0.013453398831188679,...",совместимость
5,5,"АО «ИнфоТеКС», 127083, Москва, улица Мишина, д...",533,65,133.25,"[-0.010863716714084148, -0.03315876051783562, ...",совместимость

In [176]:
# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(dfi)
embeddings_df_save_path = "all_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

In [177]:
import random

import torch
import numpy as np 
import pandas as pd

device = "cuda" 

# Import texts and embedding df
text_chunks_and_embedding_df = pd.read_csv("all_embeddings_df.csv")

text_chunks_and_embedding_df.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding,product
0,1,ViPNet Coordinator HW 5.Подготовка к работе | ...,1274,159,318.5,"[0.0060768756084144115, -0.042224615812301636,...",подготовка
1,1,NAT позволяет решить две задачи:  Подключение...,930,112,232.5,"[-0.007902384735643864, -0.02230028621852398, ...",подготовка
2,2,ViPNet Coordinator HW 5.Подготовка к работе | ...,234,35,58.5,"[0.008719977922737598, -0.03479960188269615, -...",подготовка
3,3,ViPNet Coordinator HW 5.Подготовка к работе | ...,1222,149,305.5,"[-0.022762130945920944, -0.0357675738632679, 0...",подготовка
4,3,Событие срабатывания правила IPS регистрируетс...,314,43,78.5,"[-0.017361363396048546, 0.0026617932599037886,...",подготовка

In [178]:
a = text_chunks_and_embedding_df['embedding'][0]
a

'[0.0060768756084144115, -0.042224615812301636, 0.03113720938563347, -0.0034974946174770594, 0.030625909566879272, 0.04431794956326485, 0.04278827831149101, -0.03131306171417236, 0.004370264243334532, -0.0018111745594069362, 0.00297339609824121, -0.006709175184369087, -0.029058067128062248, -0.012864574790000916, 0.003598205279558897, 0.0717412605881691, -0.019464312121272087, -0.0007522632367908955, -0.0032086626160889864, 0.01624186895787716, 0.0008060901891440153, 0.009114071726799011, 0.0480445958673954, 0.02245764434337616, 0.034263525158166885, 0.04395190626382828, -0.034268900752067566, 0.0030069672502577305, 0.005287116393446922, -0.02772851102054119, 0.02152939699590206, -0.009112270548939705, -0.00979863665997982, -0.02937152236700058, 0.04139349237084389, 0.031725164502859116, -0.040957432240247726, 0.03895822912454605, -0.01946321502327919, -0.02197045274078846, -0.016633104532957077, -0.02320767380297184, -0.01998130977153778, -0.006218431517481804, -0.008803882636129856, -0.02994401939213276, 0.028134865686297417, 0.015702856704592705, 0.00144611531868577, -0.00785854272544384, -0.0025085187517106533, 0.0439089871942997, -0.034353289753198624, 0.0313943475484848, -0.02801305241882801, 0.016785599291324615, 0.03519825637340546, 0.021705415099859238, 0.025769932195544243, -0.025991540402173996, -0.0212473813444376, 0.008975287899374962, 0.022720109671354294, -0.066453717648983, 0.016650615260004997, -0.007216837257146835, 0.04938088729977608, -0.015806056559085846, -0.03244060277938843, -0.0030955523252487183, -0.009433072991669178, -0.022350648418068886, -0.01170409843325615, -0.045132916420698166, 0.016555165871977806, -0.008772470988333225, 0.008692649193108082, -0.0008805211400613189, -0.03294992446899414, 0.009612469002604485, 0.027394410222768784, 0.0032988206949084997, -0.002911511342972517, 0.014810730703175068, 0.03041791170835495, 0.0004336730344220996, 0.01855514384806156, -0.017544277012348175, 0.025705521926283836, 0.042589858174324036, -0.0038632412906736135, -0.005611466243863106, 0.033515844494104385, 0.021463776007294655, 0.010158495046198368, -0.000411986984545365, 0.006301701068878174, 0.06168629974126816, -0.04053046926856041, -0.009644276462495327, 0.007408920209854841, 0.0647508054971695, 0.009367469698190689, -0.04259531944990158, -0.04472189024090767, -0.005920845549553633, -0.014502010308206081, -0.016192732378840446, -0.013506494462490082, 0.0013486059615388513, -0.022479213774204254, -0.026900772005319595, 0.00012219410564284772, -0.03441450372338295, -0.012998909689486027, 0.01980215311050415, -0.010250616818666458, -0.06290433555841446, -0.019796667620539665, 0.014740176498889923, 0.028171582147479057, -0.0034027567598968744, 0.005848370958119631, 0.014915560372173786, -0.03132341802120209, -0.00021545146591961384, -0.0009174481383524835, 0.005424370989203453, 0.0008991997456178069, 0.027158740907907486, 0.0005557542899623513, 0.00839688815176487, 0.018054848536849022, 0.003916617948561907, -0.025719119235873222, -0.018362434580922127, 0.009433134458959103, -0.016987597569823265, 0.010710950940847397, 0.022218702360987663, 0.03902730718255043, -0.007146815303713083, -0.007238788064569235, 0.0005248653469607234, 0.0213931892067194, -0.013320773839950562, -0.011046510189771652, -0.014677061699330807, 0.02903912588953972, 0.061570893973112106, -0.0026256171986460686, -0.0007891883724369109, -0.03246642276644707, 0.0016043222276493907, 0.043498408049345016, -0.008047813549637794, -0.013415324501693249, 0.025535842403769493, 0.005982653237879276, 0.002276578452438116, 0.006496076472103596, 0.029219692572951317, -0.02342897653579712, 0.006403129082173109, -0.009707923978567123, 0.02663072571158409, -0.055710501968860626, 0.046235911548137665, -0.008671632967889309, -0.014786400832235813, -0.048395078629255295, 0.020754128694534302, -0.030514581128954887, 0.027461150661110878, -0.014072034507989883, 0.011927977204322815, -0.002230881480500102, -0.016094814985990524, -0.0011712422128766775, -0.01955493725836277, -0.014234733767807484, -0.0016250447370111942, 0.050825830549001694, 0.048394668847322464, 0.004115042742341757, 0.02883012406527996, 0.010616190731525421, 0.020470263436436653, 0.013350444845855236, 0.010499528609216213, 0.034539639949798584, -0.0354623980820179, -0.04248980060219765, 0.01578383706510067, 0.048155009746551514, -0.010481120087206364, -0.018798651173710823, -0.022886205464601517, 0.00634407764300704, 0.014541666023433208, 0.005859949626028538, -0.018480291590094566, -0.00396092189475894, 0.04229651391506195, 0.015824446454644203, -0.03593931719660759, -0.04582076892256737, 0.024632271379232407, 0.037907470017671585, 0.026165463030338287, -0.044638123363256454, -0.0011045861756429076, -0.025530219078063965, -0.033209316432476044, -0.0016361941816285253, -0.008775093592703342, 0.026311973109841347, -0.046993546187877655, 0.021865105256438255, -0.0013617663644254208, 0.06386766582727432, 0.021902266889810562, 0.02913573384284973, 0.01609577052295208, 0.022473428398370743, 0.020991014316678047, 0.030525648966431618, -0.04471355304121971, -0.023723818361759186, 0.002423902740702033, -0.02715284749865532, 0.03935025632381439, 0.015890834853053093, 0.02444593608379364, 0.016154108569025993, 0.038615498691797256, -0.021512623876333237, -0.021488545462489128, 0.04242600500583649, 0.05277865752577782, 0.017163004726171494, -0.0001778676814865321, 0.02000923827290535, -0.04387173801660538, 0.00039634882705286145, -0.020307006314396858, 0.030720049515366554, -0.005263059865683317, -0.020997436717152596, 0.0004934935132041574, -0.01967540755867958, 0.01862224005162716, -0.01903894729912281, 0.017282554879784584, 0.003026440041139722, 0.06472956389188766, -0.014041580259799957, -0.022756585851311684, 0.036945704370737076, -0.0004332616808824241, 0.05917929485440254, 0.005870473571121693, 0.046240147203207016, 0.021659575402736664, -0.018910037353634834, -0.044670820236206055, 0.002572963247075677, -0.044061996042728424, 0.0013252435019239783, -0.014121811836957932, 0.016038330271840096, 0.02063678577542305, 0.04629633203148842, -0.024577373638749123, -0.04287852346897125, 0.028299659490585327, 0.015791676938533783, 0.007571975234895945, -0.0010456888703629375, 0.004260822664946318, -0.01899329572916031, -0.025539064779877663, 0.03499731421470642, 0.01737135834991932, 0.025753004476428032, -0.04042595252394676, 0.005936282686889172, -0.008319261483848095, -0.014753836207091808, -0.026760414242744446, -0.011860118247568607, 0.007968137972056866, 0.0009866099571809173, 0.021623583510518074, -0.02036081999540329, -0.0196323711425066, -0.019093208014965057, -0.0009250526200048625, -0.002591380849480629, -0.03818092495203018, 0.0053514158353209496, -0.028531447052955627, 0.029206806793808937, 0.018093489110469818, -0.04755108803510666, 0.014950530603528023, -0.03287426754832268, -0.03698283061385155, 0.026144662871956825, -0.051041796803474426, 0.04013959690928459, -0.030578218400478363, 0.01848214864730835, -0.03662751615047455, 0.02923806942999363, -0.06626633554697037, -0.01243803184479475, 0.01798647828400135, -0.0013056488242000341, -0.037886738777160645, 0.006664546672254801, -0.010616370476782322, 0.05325039476156235, -0.04244321212172508, 0.023571161553263664, 0.01111194770783186, 0.04512745514512062, 0.01231854036450386, 0.003988210577517748, -0.014087769202888012, 0.012662716209888458, 0.015610657632350922, 0.020848676562309265, 0.03382193297147751, -0.013840775936841965, 0.004552950616925955, -0.008917857892811298, 0.0004094263131264597, -0.01161515899002552, 0.020432181656360626, -0.016961636021733284, 0.03208426758646965, 0.027013491839170456, 0.03097439743578434, 0.02495655044913292, -0.003376733511686325, -0.020466867834329605, -0.0547657385468483, -0.06402052938938141, -0.00975493248552084, -0.055095650255680084, -0.007522326894104481, 0.032132431864738464, -0.022649381309747696, 0.00643574446439743, 0.027515443041920662, -0.02485133893787861, -0.01934162527322769, -0.012238153256475925, 0.04264594614505768, -0.012533015571534634, 0.017818361520767212, -0.02121136523783207, 0.01600073091685772, -0.0007374140550382435, -0.012483487837016582, -0.011476931162178516, -0.017845217138528824, -0.00028142909286543727, 0.023815268650650978, -0.012388207018375397, -0.015470271930098534, -0.005241040140390396, 3.5537661460693926e-05, -0.044056158512830734, -0.02748885005712509, 0.007349773775786161, -0.009928286075592041, 0.02069888822734356, -0.020444383844733238, -0.0035848210100084543, -0.03151119127869606, -0.008138797245919704, 0.005692004691809416, -0.0010187455918639898, 0.01308632642030716, 0.019207999110221863, -0.01455982867628336, -0.005346757359802723, 0.011548135429620743, 0.03737883269786835, 0.013217690400779247, 0.004739139229059219, 0.010961274616420269, 0.002506962278857827, -0.04118223860859871, -0.009191092103719711, 0.0048001310788095, -0.007509330287575722, -0.024646276608109474, -0.006208206061273813, -0.05731950327754021, 0.0688280239701271, -0.07903751730918884, 0.034578923135995865, -0.009135079570114613, 0.012960495427250862, 0.016504434868693352, -0.07265672087669373, 0.026222994551062584, -0.0012476254487410188, -0.01938071846961975, 0.028940722346305847, 0.042135316878557205, -0.0025147823616862297, 0.019735734909772873, 0.029399879276752472, -0.03152870386838913, 0.014965777285397053, -0.027320321649312973, 0.0242423415184021, -0.008825301192700863, 0.01623210310935974, 0.06316544115543365, 0.046050406992435455, -0.029906826093792915, 0.00825861468911171, 0.0076796929351985455, 0.025624040514230728, 0.04933936893939972, 0.019005529582500458, 0.013954797759652138, -0.0036466505844146013, -0.017438914626836777, 0.029284529387950897, 4.0651946619618684e-05, 0.01247304305434227, -0.0028372027445584536, 0.016840621829032898, 0.01401958055794239, 0.04738811403512955, -0.01104713138192892, -0.005786217749118805, 0.022510165348649025, 0.0038249038625508547, -0.018977142870426178, 0.03240612521767616, -0.05439645051956177, -0.023459767922759056, 0.046380676329135895, 0.013368966057896614, 0.02090405486524105, -0.035132069140672684, 0.030428966507315636, 0.007699782960116863, 0.014781483449041843, 0.006185681559145451, 0.0030821433756500483, 0.008488344959914684, 0.011465458199381828, -0.023986462503671646, -0.01802719198167324, 0.018261130899190903, 0.04694037884473801, -0.04392865672707558, 0.006253170780837536, 0.03573838993906975, 0.032617755234241486, 0.01354528870433569, -0.02760450914502144, -0.028120165690779686, -0.023906586691737175, 0.019675957038998604, -0.025581488385796547, -0.0486932210624218, -0.012649701908230782, -0.059489063918590546, -0.006948716472834349, 0.0021135741844773293, -0.005490990821272135, -0.025323286652565002, -0.01816134713590145, -0.05516127124428749, 0.004503384232521057, -0.02841765433549881, 0.0016666275914758444, 0.004132919013500214, -0.04186568781733513, 0.0019164138939231634, 0.029731953516602516, 0.007880066521465778, -0.04307381808757782, 0.018156884238123894, -0.011316756717860699, -0.02421051636338234, 0.011686847545206547, 0.03395945951342583, -0.030563026666641235, -0.025934018194675446, -0.016356755048036575, -0.01612110063433647, -0.006793797016143799, 0.0030581329483538866, -0.007466715760529041, 0.01669406332075596, -0.0413702093064785, 0.011056785471737385, -0.010015309788286686, 0.022853249683976173, 0.007187003269791603, 0.015008878894150257, 0.021827170625329018, 0.025904132053256035, 0.020273344591259956, 0.03041921742260456, -0.05040454864501953, 0.047901179641485214, -0.04549902677536011, 0.026382818818092346, 0.026716580614447594, -0.007804398890584707, 0.03405848890542984, -0.007070586550980806, 0.022380052134394646, -0.015221092849969864, -0.0049573457799851894, 0.00802887137979269, -0.01750864088535309, -0.01450127363204956, 0.03929738327860832, -0.006997621618211269, -0.007216424681246281, -0.011673852801322937, 0.0009494347032159567, 0.0011802000226452947, -0.04244813695549965, 0.0023771519772708416, 0.011780904605984688, -0.036848828196525574, -0.028706694021821022, -0.023765085265040398, -0.01748279295861721, 0.0013469042023643851, 0.011012912727892399, -0.020252922549843788, 0.007394470274448395, 0.021859915927052498, 0.042345840483903885, -0.04608365520834923, 0.018832193687558174, -0.01039070077240467, 0.0034355095122009516, -0.006239951588213444, -0.002468972932547331, -0.01325911469757557, -0.039840951561927795, 0.024748723953962326, -0.027709195390343666, -0.008677705191075802, 0.02569354698061943, 0.0003352698404341936, 0.03408278152346611, -0.016170216724276543, 0.038975976407527924, -0.059675317257642746, 0.020337969064712524, 0.03227842226624489, 0.06349050998687744, 0.020032543689012527, -0.003935910761356354, 0.0009406162425875664, -0.49815696477890015, 0.009718837216496468, 0.009516298770904541, -0.002564396243542433, -0.00815398246049881, -0.0011742457281798124, -0.01361433882266283, -0.03503267467021942, -0.050043076276779175, 0.015534463338553905, 0.020030949264764786, 0.009326129220426083, -0.020948417484760284, 0.019931625574827194, -0.023080019280314445, 0.02020888961851597, 0.008050221018493176, 0.011149373836815357, -0.06443651765584946, 0.0003949809761252254, 0.011824365705251694, -0.01670638658106327, -0.05676450952887535, -0.01673205755650997, -0.002568567171692848, 0.0003910598752554506, 0.007195567712187767, 0.05838910862803459, -0.02278800867497921, -0.010318689048290253, 0.017534619197249413, 0.0072957300581038, -0.030646851286292076, -0.02585763670504093, -0.04064690321683884, 0.01639043726027012, 0.012133654206991196, 0.01700454019010067, -0.012121938169002533, 0.01524229533970356, -0.002009230898693204, 0.012724479660391808, 0.010750679299235344, -0.01767800934612751, 0.019915683194994926, -0.014688301831483841, -0.002321425126865506, -0.00046799200936220586, -0.007599284872412682, 0.03893345594406128, 0.013735178858041763, -0.02256595715880394, -9.077296999748796e-05, 0.04450326785445213, -0.0028704635333269835, -0.016111275181174278, -0.016468841582536697, 0.012147730216383934, -0.012823445722460747, -0.02551959455013275, 0.06327471882104874, 0.0018538678996264935, 0.021008698269724846, 0.0010278457775712013, 0.07282295823097229, 0.000399651238694787, -0.006257664877921343, 0.0511905774474144, -0.05013057217001915, -0.015841953456401825, 0.020831024274230003, -0.004944199230521917, -0.000486866949358955, 0.048052601516246796, 0.02130076289176941, 0.03694745525717735, -0.028966646641492844, -0.0028589717112481594, -0.018500659614801407, 0.011187644675374031, 0.05829056724905968, 0.01655655913054943, -0.05018995702266693, 0.04302915558218956, 0.012505118735134602, 0.043344710022211075, 0.03393751382827759, -0.025475826114416122, 0.026181014254689217, -0.012536498717963696, 0.01841133087873459, -0.0444553904235363, -0.029327092692255974, 0.0035909104626625776, 0.0014602947048842907, -0.10570339113473892, -0.010723811574280262, 0.016938671469688416, -0.04286317899823189, -0.01272625382989645, 0.02787613682448864, -0.006662057712674141, -0.024800557643175125, -0.006002249661833048, -0.01846502535045147, 0.016244668513536453, 0.030758336186408997, 0.0008863799157552421, -0.005368535406887531, 0.009469890967011452, 0.04037484526634216, -0.014457332901656628, 0.004574672784656286, 0.006411699578166008, 0.025016633793711662, 0.043234214186668396, 0.07412337511777878, 0.001686709700152278, -0.013180764392018318, 0.012942885980010033, -0.013668275438249111, 0.004081111401319504, -0.024611644446849823, -0.002751051215454936, -0.030625980347394943, 0.016715586185455322, -0.02355877310037613, -0.022079190239310265, -0.0190651323646307, -0.023797614499926567, -0.008108320645987988, -0.015798700973391533, 0.005586485378444195, 0.026561209931969643, -0.023744158446788788, -0.03980014845728874, 0.001662913360632956, 0.015185371041297913, 0.020018916577100754, -0.006744195707142353, 0.03797965869307518, 0.025327567011117935, 0.016272930428385735, 0.014574307948350906, -0.06040452420711517, -0.012021511793136597, -0.03044002875685692, -0.016652364283800125, -0.03828077390789986, 0.05188300088047981, 0.015872526913881302, 0.0014772738795727491, 0.009694226086139679, 0.008947770111262798, -0.03515540435910225, -0.009126807563006878, 0.036607518792152405, -0.025403939187526703, -0.0017658545402809978, -0.01475496031343937, -0.014353147707879543, 0.013733197003602982, -0.004443163983523846, 0.031966403126716614, -0.0036312704905867577, -0.016544481739401817, 0.027327008545398712, 0.006221783813089132, 0.0027903749141842127, -0.0011592134833335876, -0.005494952201843262, -0.004299970343708992, -0.013126295059919357, -0.004056175705045462, -0.045163076370954514, 0.018253028392791748, -0.019736921414732933, 0.037643369287252426, -0.0031244067940860987, 0.018614599481225014, 0.02830861322581768, 0.045453161001205444, 0.02370345965027809, -0.028835691511631012, 0.056254271417856216, -0.024195287376642227, 0.009099854156374931, -0.01243840716779232, 0.0033903492148965597, -0.03224226087331772, 0.014719261787831783, 0.011461838148534298, 0.03516675531864166, 0.0042846668511629105, 0.0091737424954772, -0.0001572657492943108, -0.010746299289166927, -0.05952432379126549, -0.02640542946755886, -0.02520022727549076, 0.01347183808684349, 0.013400079682469368, -0.0038524135015904903, 0.0305075254291296, 0.02225043810904026, -0.010052166879177094, -0.006646936759352684, 0.017486995086073875, -0.04398107901215553, 0.031247755512595177, -0.005749853327870369, 0.03578364849090576, 0.010269800201058388, -0.01815379410982132, -0.016249343752861023, -0.005882442928850651, -0.002719478216022253, 0.0062529100105166435, -0.0077766417525708675, 0.020586885511875153, -0.020643897354602814, 0.0025174280162900686, -0.03043759986758232, 0.005116691812872887, 0.008390989154577255, 0.002159389201551676, 0.016196340322494507, -0.0203859843313694, 0.007301490753889084, -0.01322865579277277, -0.024511555209755898, 0.02656589075922966, -0.04215868562459946, -0.01396283507347107, -0.018522178754210472, -0.04625988006591797, -0.023473436012864113, -0.03384832292795181, 0.014711354859173298, -0.014832052402198315, 0.0062956479378044605, -0.011993023566901684, -0.007817485369741917, -0.008484558202326298, -0.022663353011012077, 0.0012727000284940004, -0.023640722036361694, -0.009155448526144028, -0.02952418103814125, 0.0040218401700258255, 0.01205255277454853, 0.026044683530926704, -0.012332271784543991, 0.04226762056350708, -0.01877768151462078, -0.05684765428304672, 0.008744756691157818, -0.031285498291254044, 0.03190676122903824, -0.0451468862593174, -0.020384712144732475, 0.03355856239795685, 0.007367821875959635, 0.0008792296866886318, 0.014424934983253479, 0.03201554715633392, -0.048402659595012665, -0.011380632407963276, -0.005107706878334284, -0.004914965480566025, -0.032231468707323074, -0.0011722773779183626, -0.0030006319284439087, -0.056095320731401443, -0.02392582781612873, 0.021435482427477837, -0.01234462670981884, 0.04108709096908569, -0.035533562302589417, 0.0027958774007856846, -0.014708072878420353, 0.06885328888893127, -0.004882459528744221, 0.012466231361031532, -0.0038339635357260704, 0.0022929059341549873, 0.013237089850008488, 0.04691377654671669, 0.007750330958515406, 0.021778013557195663, 0.001001502270810306, 0.0010283339070156217, -0.0012418720871210098, 0.041540369391441345, -0.025165308266878128, 0.02765938639640808, 0.005335239693522453, 0.018588058650493622, -0.020878363400697708, 0.01665322110056877, 0.022333713248372078, 0.0804937332868576, -0.041813045740127563, 0.056597206741571426, -0.011374522000551224, -7.023353828117251e-05, -0.0032940900418907404, 0.019272252917289734, -0.0012073346879333258, 0.042154207825660706, 0.009497463703155518, -0.03557918965816498, -0.027838941663503647, -0.004934673197567463, 0.0071716029196977615, -0.04547009617090225, -0.0036714959423989058, -0.020657945424318314, 0.008100366219878197, -0.007101213559508324, 0.013387942686676979, -0.01435437984764576, 0.03184026479721069, 0.016989771276712418, -0.23204921185970306, -0.004313596524298191, -0.0150

In [179]:
b=np.fromstring(a.strip("[]"), sep=", ")
b

array([ 0.00607688, -0.04222462,  0.03113721, ..., -0.01416949,
        0.02664318,  0.01222325], shape=(1024,))